name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3  # Updated to the latest version
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build
