name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to the latest version supporting Node.js 20
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4  # Updated to the latest version supporting Node.js 20
      with:
        distribution: 'temurin'  # Updated to 'temurin' which is the new name for AdoptOpenJDK
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build
