name: Java CI with Gradle

on:
  push:
    branches: [ main, tta-assignment ]
  pull_request:
    branches: [ main, tta-assignment ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin' # This specifies the JDK distribution

    - name: Build with Gradle
      run: ./gradlew build
