name: Java CI with Maven

on:
  push:
    branches: [ main, tta-assignment ]
  pull_request:
    branches: [ main, tta-assignment ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to the latest version supporting Node.js 20
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4  # Updated to the latest version supporting Node.js 20
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test
